  window.sectionCompareData1 = {
	sectionCompareheading: "PrintBase vs Other platforms",
	sectionCompareSubHeading: `See what's best for your dropshipping or print-on-demand business`,
	dataBrand: {
		title: {
		  printBase: "PrintBase",
		  teeChip: "Teechip",
		  gearLaunch: "Gearlaunch",
		  moteefe: "Moteefe",
		}
	},
	dataCompare: {
		"Price": {
			entryPricing: {
				title: "Monthly subscription fee",
				subTitle: null,
				printBase: `<p class="isFocus">$39/month</p> All PrintBase features with no limitation`,
				teeChip: `Free`,
				gearLaunch: `Free`,
				moteefe: `Free`,
			},
			baseCostStartingFrom: {
				title: "Base cost starting from",
				subTitle: "Base cost includes printing service and products' original prices",
				printBase: `<p class="isFocus">$5.99</p>`,
				teeChip: `$6`,
				gearLaunch: `Depends on tier`,
				moteefe:`$5.49`,
			}
		},
		"Design and creation": {
			customizableCheckoutPage: {
				title: "Customizable checkout page",
				subTitle: "Visually customize the design and layout of the checkout page",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="close-icon"></span>`,
				gearLaunch: `<span class="close-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			},
			customizableProductPages: {
				title: "Customizable product pages",
				subTitle: "Flexibly customize the design and layout of product pages",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="close-icon"></span>`,
				gearLaunch: `<span class="close-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			},
			customProductFields: {
				title: "Custom product fields",
				subTitle: "Add custom fields to display more info about products",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="close-icon"></span>`,
				gearLaunch: `<span class="close-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			},
			emailCustomization: {
				title: "Email customization",
				subTitle: "Change the color, logo, and text in receipts and order confirmation emails",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			}
		},
		"Marketing & SEO": {
			abandonedCartRecovery: {
				title: "Abandoned cart recovery",
				subTitle: "Send SMS/email reminders to customers who added items to their cart without completing purchases",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="close-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			},
			discountsAndCoupons: {
				title: "Discounts and coupons",
				subTitle: "Create and manage coupons for sales and promotions",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			socialMediaIntegration:{
				title: "Social media integration",
				subTitle: "Sync products to social media to run smarter marketing campaign",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="close-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,	
			},
      		ssl: {
				title: "SSL",
				subTitle: "Secure hosting with SSL included",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			}
		},
		"Up-sell & tools": {
			upsell: {
				title: "Up-sell",
				subTitle: "Recommend customers to replace the current item in cart by a high-tier one, or suggest them relevant items to buy more",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="close-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			crossSel: {
				title: "Cross-sell",
				subTitle: "Suggest the complementary bundles, which combine frequently-bought-together products",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="close-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			quantityDiscounts: {
				title: "Quantity Discounts",
				subTitle: "Motivate customers to buy more by presenting them with irresistible combos",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="close-icon"></span>`,
				gearLaunch: `<span class="close-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			productRecommendation: {
				title: "Product Recommendation",
				subTitle: "Show recommendations based on customers' purchases & browsing history",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="close-icon"></span>`,
				gearLaunch: `<span class="close-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			}
		},
		"Payment":{
			issueRefunds:{
				title: "Issue refunds",
				subTitle: "Refund payment for orders if needed",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			payPalPayment:{
				title: "PayPal payment",
				subTitle: "Faster checkout with PayPal",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			}	
		},
		"Campaign Management": {
			multipleProductVariants:{
				title: "Multiple product variants",
				subTitle: "Sell products in different colors, sizes, and more",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			personalizationProducts: {
				title: "Personalization products",
				subTitle: "Let shoppers customize their products with personalized texts, photos and more",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="close-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			},
			customWatermark:{
				title: "Custom watermark",
				subTitle: "Auto insert logo, text to product images to protect your ideas",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="close-icon"></span>`,
				gearLaunch: `<span class="close-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			},
			bulkDuplicate: {
				title: "Bulk duplicate",
				subTitle: "Create multiple campaigns at a glance",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			},
		},
		"Store management": {
			staffAccounts:{
				title: "Staff accounts (collaborators)",
				subTitle: "Invite colleagues and clients to manage products and fulfill orders",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			mobileStoreManagement:{
				title: "Mobile store management",
				subTitle: "Manage orders from any device",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			staffPermissions:{
				title: "Staff permissions",
				subTitle: "Set different roles for staff to manage products, fulfill orders, and operate business",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			multiLanguageSites: {
				title: "Multi-language sites",
				subTitle: "Translate your site to end-customer's language",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			},
			multiCurrencysites: {
				title: "Multi-currency sites",
				subTitle: "Display price in local currency based on the customer's region",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="close-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="close-icon"></span>`,
			},
		},
		"Shipping": {
			manualShippingRules: {
				title: "Manual shipping rules",
				subTitle: "Define shipping rules based on region and products",
				printBase: `<span class="checked-icon"></span>`,
				teeChip: `<span class="checked-icon"></span>`,
				gearLaunch: `<span class="checked-icon"></span>`,
				moteefe: `<span class="checked-icon"></span>`,
			}
		},
	},
	targetShowSectionCompare: ".target-section-compare",
}